# -*- coding: utf-8 -*-
"""MMdet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUI5FxVbGBQyTxcPYX3WipDLhmafir3w
"""

!pip3 install openmim
!mim install mmcv-full

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/open-mmlab/mmdetection.git
# %cd mmdetection
!pip install -e .

!pip install mmdet
!pip install mmcv

import mmdet
print(mmdet.__version__)

!python demo/video_demo.py \
    /content/drive/MyDrive/4K\ Video\ of\ Highway\ Traffic!.mp4 \
    /content/mmdetection/configs/yolo/yolov3_d53_320_273e_coco.py \
    /content/drive/MyDrive/Yolo.pth \
    --out /content/drive/MyDrive/videores1.mp4

